module.exports = [
    {   
       name: 'Slurricane Flower',
       img: 'https://i.imgur.com/QTscko6.jpg',
       productType: 'Flower',
       strain: 'Slurricane',
       indicaSativa: 'Indica',
       thc: 21,
       dispensary: 'Reef',
       company: 'Tryke Companies', 
       rating: 5,
       comments: 'Great flavor, burns easily, relaxed high',
    },
    {   
       name: 'Double Dream Shatter',
       img: 'https://i.imgur.com/FrpyhGW.jpg',
       productType: 'Shatter',
       strain: 'Double Dream',
       indicaSativa: 'Sativa',
       thc: '79.97',
       dispensary: 'Silver State Relief',
       company: 'Cannavative',
       rating: 4,
       comments: 'Potent, great smell and flavor, motivated high',
    },
    {   
       name: 'Strawberry Fields Pre Roll',
       img: 'https://i.imgur.com/XbRJOk4.jpg',
       productType: 'Joint',
       strain: 'Strawberry Fields',
       indicaSativa: 'Hyrbrid',
       thc: '13.54',
       dispensary: 'Mint',
       company: 'MadMen',
       rating: 1,
       comments: 'Did not like, felt high anxiety',
    },
   ];