module.exports = [
    {   
       name: 'Slurricane Flower',
       img: 'https://i.imgur.com/QTscko6.jpg',
       productType: 'Flower',
       strain: 'Slurricane',
       indicaSativa: 'Indica',
       thc: 21,
       dispensary: 'Reef',
       company: 'Tryke Companies', 
       rating: 5,
       comments: 'Great flavor, burns easily, relaxed high',
    },
    {   
       name: 'Double Dream Shatter',
       img: 'https://i.imgur.com/FrpyhGW.jpg',
       productType: 'Shatter',
       strain: 'Double Dream',
       indicaSativa: 'Sativa',
       thc: '79.97',
       dispensary: 'Silver State Relief',
       company: 'Cannavative',
       rating: 4,
       comments: 'Potent, great smell and flavor, motivated high',
    },
    {   
       name: 'Strawberry Fields Pre Roll',
       img: 'https://i.imgur.com/XbRJOk4.jpg',
       productType: 'Joint',
       strain: 'Strawberry Fields',
       indicaSativa: 'Hyrbrid',
       thc: '13.54',
       dispensary: 'Mint',
       company: 'MadMen',
       rating: 1,
       comments: 'Did not like, felt high anxiety',
    },
    
   {   
      name: 'Sea Salt Chocolate Cookies',
      img: 'https://i.imgur.com/q1cEOcT.jpg',
      productType: 'Edible',
      strain: 'mix',
      indicaSativa: 'Sativa',
      thc: 10,
      dispensary: 'Rise',
      company: 'Silver State Trading', 
      rating: 5,
      comments: 'Delicious, euphoric feeling, body high',
   },
   {   
      name: 'Tropical Gummiez',
      img: 'https://i.imgur.com/yXR5yaw.jpg',
      productType: 'Edible',
      strain: 'mix',
      indicaSativa: 'Indica',
      thc: 10,
      dispensary: 'Herb',
      company: 'Kiva Confections', 
      rating: 4,
      comments: 'Taste pretty good, allowed for good sleep',
   },
   ];